name: Build ESP-Matter for ESP32-H2
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get remove -y '^dotnet-.*' '^llvm-.*' 'php.*' azure-cli google-chrome-stable firefox powershell mono-devel 2>/dev/null || true
          sudo apt-get autoremove -y
          sudo apt-get clean
          df -h
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
      
      - name: Set up ESP-IDF
        run: |
          mkdir -p ~/esp
          cd ~/esp
          git clone --recursive --branch v5.4.1 --depth 1 https://github.com/espressif/esp-idf.git
          cd esp-idf
          ./install.sh esp32h2
      
      - name: Build Matter project
        run: |
          source ~/esp/esp-idf/export.sh
          cd examples/light
          idf.py set-target esp32h2
          idf.py build
      
      - name: Upload firmware binaries
        uses: actions/upload-artifact@v4
        with:
          name: esp32h2-firmware
          path: |
            examples/light/build/*.bin
            examples/light/build/*.elf
            examples/light/build/bootloader/bootloader.bin
            examples/light/build/partition_table/partition-table.bin
