name: Build ESP-Matter for ESP32-H2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'


      - name: Set up ESP-IDF
        uses: espressif/github-actions/setup-idf@v1
        with:
          version: v5.3
          targets: esp32h2

      - name: Build Matter project
        run: |
          cd examples/light
          idf.py set-target esp32h2
          idf.py build

      - name: Upload firmware binaries
        uses: actions/upload-artifact@v4
        with:
          name: esp32h2-firmware
          path: |
            examples/light/build/*.bin
